celib: ce_string_set_data_inrange
ce_string_append
ce_string_append_data
ce_string_append_data_inrange
ce_string_append_inrange
ce_string_clear
ce_string_compare
ce_string_compare_data
ce_string_compare_data_inrange
ce_string_compare_inrange
ce_string_concat
ce_string_concat_data
ce_string_concat_data_inrange
ce_string_concat_inrange
ce_string_copy
ce_string_copy_inrange
ce_string_delete
ce_string_get_data
ce_string_get_data_inrange
ce_string_get_length
ce_string_get_length_inrange
CE_STRING_INITIAL
ce_string_isequal
ce_string_isequal_inrange
ce_string_new
ce_string_new_with_data
ce_string_new_with_data_inrange
ce_string_reverse
ce_string_reverse_inrange
ce_string_set_data
ce_string_set_data_inrange
ce_string_swap
ce_string_tolower
ce_string_tolower_inrange
ce_string_toupper
ce_string_toupper_inrange
CeString* ce_string_set_data_inrange (CeString * self, const CeUChar * data, CeInt start, CeInt end)
Setting the data in range in CeString Object.
Parameters:
self The CeString Object
data A String Object
start The first char is 1, the second is 2, blah blah blah.
end The last char is -1 or the length of String Object
Returns:
The CeString Object
Definition at line 153 of file cestring.c.
References CE_RANGE_INITIAL, and CE_STRING_INITIAL.
Referenced by ce_string_copy_inrange(), ce_string_new_with_data_inrange(), and ce_string_set_data().
{
        CE_STRING_INITIAL();
        CeInt length = strlen(data);
        CE_RANGE_INITIAL(start, end, length);
        length = end - start + 1;
        /* Free the CeString Object first */
        if(0 != selfp->len) {
                free(self->data);
        }
        selfp->len = length;
        selfp->data = (CeUChar *) malloc( sizeof(CeUChar) * (length + 1) );
        /* Now let's copy new string to our CeString */
        memcpy(selfp->data, data + start, length);
        selfp->data[length] = '\0';   /* end of line */
        return self;
}