celib: /home/coldnew/WorkSpace/celib/src/cestring.c File Reference
/home/coldnew/WorkSpace/celib/src/cestring.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "cetypes.h"
#include "cestring.h"
#include "ceswap.h"
#include "cemacros.h"
Data Structures
struct CeStringP
Defines
#define CE_STRING_INITIAL() selfp = (CeStringP *) self;
Functions
CeString * ce_string_new (void)
Initial the CeString Object without setting any data.
CeString * ce_string_new_with_data (const CeUChar *data)
Initial the CeString Object and set the data and length.
CeString * ce_string_new_with_data_inrange (const CeUChar *data, CeInt start, CeInt end)
Initial the CeString Object and set the data in range.
void ce_string_delete (CeString *self)
Totally free the CeString Object.
void ce_string_clear (CeString *self)
Clear data and length in CeString Object.
CeString * ce_string_set_data (CeString *self, const CeUChar *data)
Setting the data in CeString Object.
CeString * ce_string_set_data_inrange (CeString *self, const CeUChar *data, CeInt start, CeInt end)
Setting the data in range in CeString Object.
CeUChar * ce_string_get_data (CeString *self)
Get the data of CeString Object.
CeUChar * ce_string_get_data_inrange (CeString *self, CeInt start, CeInt end)
Get the data of CeString Object in range.
CeInt ce_string_get_length (CeString *self)
Get the length of CeString Object.
CeInt ce_string_get_length_inrange (CeString *self, CeInt start, CeInt end)
Get the length of CeString Object in range.
CeString * ce_string_reverse (CeString *self)
Reverse the data in CeString Object.
CeString * ce_string_reverse_inrange (CeString *self, CeInt start, CeInt end)
Reverse the data in CeString Object in range.
CeString * ce_string_toupper (CeString *self)
Make all the cahracters in CeString object to uppercase.
CeString * ce_string_toupper_inrange (CeString *self, CeInt start, CeInt end)
Make the cahracters in CeString object in range to uppercase.
CeString * ce_string_tolower (CeString *self)
Make all the cahracters in CeString object to lowercase.
CeString * ce_string_tolower_inrange (CeString *self, CeInt start, CeInt end)
Make the cahracters in CeString object in range to lowercase.
CeInt ce_string_compare (CeString *selfA, CeString *selfB)
Compare two CeString Object.
CeInt ce_string_compare_inrange (CeString *selfA, CeString *selfB, CeInt start, CeInt end)
Compare two CeString Object in range.
CeInt ce_string_compare_data (CeString *self, CeUChar *data)
Compare the data in CeString Object with another String Object.
CeInt ce_string_compare_data_inrange (CeString *self, CeUChar *data, CeInt start, CeInt end)
Compare the data in CeString Object with another String Object in range.
CeBool ce_string_isequal (CeString *selfA, CeString *selfB)
Test if two CeString Object is equal or not.
CeBool ce_string_isequal_inrange (CeString *selfA, CeString *selfB, CeInt start, CeInt end)
Test if two CeString Object is equal or not in range.
CeString * ce_string_copy (CeString *dst, CeString *src)
Copy the second CeString Object to the first one.
CeString * ce_string_copy_inrange (CeString *dst, CeString *src, CeInt start, CeInt end)
Copy the second CeString Object to the first one in range.
void ce_string_swap (CeString *selfA, CeString *selfB)
Swap two CeString Object.
CeString * ce_string_concat (CeString *dst, CeString *src)
Concat two CeString Object.
CeString * ce_string_concat_inrange (CeString *dst, CeString *src, CeInt start, CeInt end)
Concat two CeString Object in range.
CeString * ce_string_concat_data (CeString *self, CeUChar *data)
Concat a data to CeString Object.
CeString * ce_string_concat_data_inrange (CeString *self, CeUChar *data, CeInt start, CeInt end)
Concat a data to CeString Object in range.
CeString * ce_string_append (CeString *dst, CeString *src)
Append data into CeString Object another one.
CeString * ce_string_append_inrange (CeString *dst, CeString *src, CeInt start, CeInt end)
Append data into CeString Object another one in range.
CeString * ce_string_append_data (CeString *self, CeUChar *data)
Append data to a CeString Object.
CeString * ce_string_append_data_inrange (CeString *self, CeUChar *data, CeInt start, CeInt end)
Append data to a CeString Object in range.
Define Documentation
#define CE_STRING_INITIAL () selfp = (CeStringP *) self;
Definition at line 46 of file cestring.c.
Referenced by ce_string_clear(), ce_string_delete(), ce_string_get_data_inrange(), ce_string_new(), ce_string_reverse_inrange(), ce_string_set_data_inrange(), ce_string_tolower_inrange(), and ce_string_toupper_inrange().
Function Documentation
CeString* ce_string_append (CeString * dst, CeString * src) [inline]
Append data into CeString Object another one.
Parameters:
dst A CeString Object
src A CeString Object
Returns:
The CeString Object
Definition at line 611 of file cestring.c.
References ce_string_append_data_inrange().
{
        return ce_string_append_data_inrange(dst, src->data, 1, -1);
}
CeString* ce_string_append_data (CeString * self, CeUChar * data) [inline]
Append data to a CeString Object.
Parameters:
self A CeString Object
data A String Object
Returns:
The CeString Object
Definition at line 642 of file cestring.c.
References ce_string_append_data_inrange().
{
        return ce_string_append_data_inrange(self, data, 1, -1);
}
CeString* ce_string_append_data_inrange (CeString * self, CeUChar * data, CeInt start, CeInt end)
Append data to a CeString Object in range.
Parameters:
self A CeString Object
data A String Object
start The first char is 1, the second is 2, blah blah blah.
end The last char is -1 or the length of String Object
Returns:
The CeString Object
Definition at line 657 of file cestring.c.
References CE_RANGE_INITIAL, and ce_string_set_data().
Referenced by ce_string_append(), ce_string_append_data(), and ce_string_append_inrange().
{
        CeInt data_len = strlen(data);
        CE_RANGE_INITIAL(start, end, data_len);
        CeInt new_len = self->len + data_len;
        CeInt cpy_len = end - start + 1;
        CeUChar *new_data = (CeUChar *) malloc( sizeof(CeUChar) * (new_len + 1) );
        /* Copy old data to new one */
        memcpy(new_data, data, data_len);
        memcpy(new_data + data_len, self->data, self->len);
        new_data[new_len] = '\0';   /* end of line */
        ce_string_set_data(self, new_data);
        return self;
}
CeString* ce_string_append_inrange (CeString * dst, CeString * src, CeInt start, CeInt end) [inline]
Append data into CeString Object another one in range.
Parameters:
dst A CeString Object
src A CeString Object
start The first char is 1, the second is 2, blah blah blah.
end The last char is -1 or the length of String Object
Returns:
The CeString Object
Definition at line 627 of file cestring.c.
References ce_string_append_data_inrange().
{
        return ce_string_append_data_inrange(dst, src->data, start, end);
}
void ce_string_clear (CeString * self)
Clear data and length in CeString Object.
Parameters:
self The CeString Object
Definition at line 120 of file cestring.c.
References CE_STRING_INITIAL.
Referenced by ce_string_copy_inrange().
{
        CE_STRING_INITIAL();
        free(self->data);
        selfp->data = NULL;
        selfp->len = 0;
}
CeInt ce_string_compare (CeString * selfA, CeString * selfB) [inline]
Compare two CeString Object.
Parameters:
selfA A CeString Object
selfB A CeString Object
Returns:
1 : selfA < selfB 0 : selfA == selfB -1 : selfA > selfB
Definition at line 374 of file cestring.c.
Referenced by ce_string_isequal().
{
        return strcmp(selfA->data, selfB->data);
}
CeInt ce_string_compare_data (CeString * self, CeUChar * data) [inline]
Compare the data in CeString Object with another String Object.
Parameters:
self A CeString Object
data A String Object
Returns:
1 : self->data < data 0 : self->data == data -1 : self->data > data
Definition at line 409 of file cestring.c.
{
        return strcmp(self->data, data);
}
CeInt ce_string_compare_data_inrange (CeString * self, CeUChar * data, CeInt start, CeInt end)
Compare the data in CeString Object with another String Object in range.
Parameters:
self A CeString Object
data A String Object
start The first char is 1, the second is 2, blah blah blah.
end The last char is -1 or the length of String Object
Returns:
1 : self->data < data 0 : self->data == data -1 : self->data > data
Definition at line 426 of file cestring.c.
References ce_string_delete(), ce_string_get_data_inrange(), and ce_string_new_with_data_inrange().
{
        CeString *test_data = ce_string_new_with_data_inrange(data, start, end);
        CeInt resault = strcmp(ce_string_get_data_inrange(self, start, end), test_data->data);
        ce_string_delete(test_data);
        return resault;
}
CeInt ce_string_compare_inrange (CeString * selfA, CeString * selfB, CeInt start, CeInt end) [inline]
Compare two CeString Object in range.
Parameters:
selfA A CeString Object
selfB A CeString Object
start The first char is 1, the second is 2, blah blah blah.
end The last char is -1 or the length of String Object
Returns:
1 : selfA < selfB 0 : selfA == selfB -1 : selfA > selfB
Definition at line 392 of file cestring.c.
References ce_string_get_data_inrange().
Referenced by ce_string_isequal_inrange().
{
        return strcmp(ce_string_get_data_inrange(selfA, start, end),
                      ce_string_get_data_inrange(selfB, start, end));
}
CeString* ce_string_concat (CeString * dst, CeString * src) [inline]
Concat two CeString Object.
Parameters:
dst A CeString Object
src A CeString Object
Returns:
The CeString Object
Definition at line 537 of file cestring.c.
References ce_string_concat_data_inrange().
{
        return ce_string_concat_data_inrange(dst, src->data, 1, -1);
}
CeString* ce_string_concat_data (CeString * self, CeUChar * data) [inline]
Concat a data to CeString Object.
Parameters:
self A CeString Object
data A String Object
Returns:
The CeString Object
Definition at line 567 of file cestring.c.
References ce_string_concat_data_inrange().
{
        return ce_string_concat_data_inrange(self, data, 1, -1);
}
CeString* ce_string_concat_data_inrange (CeString * self, CeUChar * data, CeInt start, CeInt end)
Concat a data to CeString Object in range.
Parameters:
self A CeString Object
data A String Object
start The first char is 1, the second is 2, blah blah blah.
end The last char is -1 or the length of String Object
Returns:
The CeString Object
Definition at line 582 of file cestring.c.
References CE_RANGE_INITIAL, and ce_string_set_data().
Referenced by ce_string_concat(), ce_string_concat_data(), and ce_string_concat_inrange().
{
        CeInt data_len = strlen(data);
        CE_RANGE_INITIAL(start, end, data_len);
        CeInt new_len = self->len + data_len;
        CeInt cpy_len = end - start + 1;
        CeUChar *new_data = (CeUChar *) malloc( sizeof(CeUChar) * (new_len + 1) );
        /* Copy old data to new one */
        memcpy(new_data, self->data, self->len);
        memcpy(new_data + self->len, data + start , cpy_len);
        new_data[new_len] = '\0';   /* end of line */
        ce_string_set_data(self, new_data);
        return self;
}
CeString* ce_string_concat_inrange (CeString * dst, CeString * src, CeInt start, CeInt end) [inline]
Concat two CeString Object in range.
Parameters:
dst A CeString Object
src A CeString Object
start The first char is 1, the second is 2, blah blah blah.
end The last char is -1 or the length of String Object
Returns:
The CeString Object
Definition at line 553 of file cestring.c.
References ce_string_concat_data_inrange().
{
        return ce_string_concat_data_inrange(dst, src->data, start, end);
}
CeString* ce_string_copy (CeString * dst, CeString * src) [inline]
Copy the second CeString Object to the first one.
Parameters:
dst A CeString Object
src A CeString Object
Returns:
The CeString Object
Definition at line 491 of file cestring.c.
References ce_string_copy_inrange().
{
        return ce_string_copy_inrange(dst, src, 1, -1);
}
CeString* ce_string_copy_inrange (CeString * dst, CeString * src, CeInt start, CeInt end)
Copy the second CeString Object to the first one in range.
Parameters:
dst A CeString Object
src A CeString Object
start The first char is 1, the second is 2, blah blah blah.
end The last char is -1 or the length of String Object
Returns:
The CeString Object
Definition at line 506 of file cestring.c.
References ce_string_clear(), and ce_string_set_data_inrange().
Referenced by ce_string_copy().
{
        ce_string_clear(dst);
        ce_string_set_data_inrange(dst, src->data, start, end);
        return dst;
}
void ce_string_delete (CeString * self)
Totally free the CeString Object.
Parameters:
self The CeString Object
Definition at line 105 of file cestring.c.
References CE_STRING_INITIAL.
Referenced by ce_string_compare_data_inrange().
{
        CE_STRING_INITIAL();
        if ( !self->data ) {
                free(self->data);
        }
        selfp->len = 0;
        free(self);
}
CeUChar* ce_string_get_data (CeString * self) [inline]
Get the data of CeString Object.
Parameters:
self The CeString Object
Returns:
The CeString Object
Definition at line 186 of file cestring.c.
{
        return (self->data);
}
CeUChar* ce_string_get_data_inrange (CeString * self, CeInt start, CeInt end)
Get the data of CeString Object in range.
Parameters:
self The CeString Object
start The first char is 1, the second is 2, blah blah blah.
end The last char is -1 or the length of String Object
Returns:
The CeString Object
Definition at line 200 of file cestring.c.
References CE_RANGE_INITIAL, CE_STRING_INITIAL, and CeStringP::data.
Referenced by ce_string_compare_data_inrange(), and ce_string_compare_inrange().
{
        CE_STRING_INITIAL();
        CE_RANGE_INITIAL(start, end, self->len);
        CeInt length = end - start + 1;
        CeUChar *data = (CeUChar *) malloc( sizeof(CeUChar) * length + 1 );
        memcpy(data, self->data + start, length);
        data[length] = '\0';    /* end of line */
        return data;
}
CeInt ce_string_get_length (CeString * self) [inline]
Get the length of CeString Object.
Parameters:
self The CeString Object
Returns:
The length of CeString Object
Definition at line 223 of file cestring.c.
{
        return (self->len);
}
CeInt ce_string_get_length_inrange (CeString * self, CeInt start, CeInt end)
Get the length of CeString Object in range.
Parameters:
selfThe CeString Object
start The first char is 1, the second is 2, blah blah blah.
end The last char is -1 or the length of String Object
Returns:
The length of CeString Object in range
Definition at line 237 of file cestring.c.
References CE_RANGE_INITIAL.
{
        CE_RANGE_INITIAL(start, end, self->len);
        return (end - start + 1);
}
CeBool ce_string_isequal (CeString * selfA, CeString * selfB) [inline]
Test if two CeString Object is equal or not.
Parameters:
selfA A CeString Object
selfB A CeString Object
Returns:
if equal : CE_TRUE else : CE_FALSE
Definition at line 446 of file cestring.c.
References CE_FALSE, ce_string_compare(), and CE_TRUE.
{
        int resault = ce_string_compare(selfA, selfB);
        if ( !resault ) {
                return CE_TRUE;
        }
        else {
                return CE_FALSE;
        }
}
CeBool ce_string_isequal_inrange (CeString * selfA, CeString * selfB, CeInt start, CeInt end) [inline]
Test if two CeString Object is equal or not in range.
Parameters:
selfA A CeString Object
selfB A CeString Object
start The first char is 1, the second is 2, blah blah blah.
end The last char is -1 or the length of String Object
Returns:
if equal : CE_TRUE else : CE_FALSE
Definition at line 470 of file cestring.c.
References CE_FALSE, ce_string_compare_inrange(), and CE_TRUE.
{
        int resault = ce_string_compare_inrange(selfA, selfB, start, end);
        if ( !resault ) {
                return CE_TRUE;
        }
        else {
                return CE_FALSE;
        }
}
CeString* ce_string_new (void)
Initial the CeString Object without setting any data.
Returns:
The CeString Object
Definition at line 54 of file cestring.c.
References CE_STRING_INITIAL.
Referenced by ce_string_new_with_data(), and ce_string_new_with_data_inrange().
{
        CeString *self  = (CeString *) malloc( sizeof(CeString) );
        if(!selfp) {
                selfp  = (CeStringP *) malloc( sizeof(CeStringP) );
        }
        CE_STRING_INITIAL();
        selfp->data = NULL;
        selfp->len = 0;
        return self;
}
CeString* ce_string_new_with_data (const CeUChar * data)
Initial the CeString Object and set the data and length.
Parameters:
data A String Object
Returns:
The CeString Object
Definition at line 77 of file cestring.c.
References ce_string_new(), and ce_string_set_data().
{
        CeString *self  = ce_string_new();
        return ce_string_set_data(self, data);
}
CeString* ce_string_new_with_data_inrange (const CeUChar * data, CeInt start, CeInt end)
Initial the CeString Object and set the data in range.
Parameters:
data A String Object
start The first char is 1, the second is 2, blah blah blah.
end The last char is -1 or the length of String Object.
Returns:
The CeString Object
Definition at line 93 of file cestring.c.
References ce_string_new(), and ce_string_set_data_inrange().
Referenced by ce_string_compare_data_inrange().
{
        CeString *self  = ce_string_new();
        return ce_string_set_data_inrange(self, data, start, end);
}
CeString* ce_string_reverse (CeString * self) [inline]
Reverse the data in CeString Object.
Parameters:
self The CeString Object
Returns:
The CeString Object
Definition at line 252 of file cestring.c.
References ce_string_reverse_inrange().
{
        return ce_string_reverse_inrange(self, 1, -1);
}
CeString* ce_string_reverse_inrange (CeString * self, CeInt start, CeInt end)
Reverse the data in CeString Object in range.
Parameters:
self The CeString Object
start The first char is 1, the second is 2, blah blah blah.
end The last char is -1 or the length of String Object
Returns:
The CeString Object
Definition at line 266 of file cestring.c.
References CE_RANGE_INITIAL, and CE_STRING_INITIAL.
Referenced by ce_string_reverse().
{
        CE_STRING_INITIAL();
        if ( 1 == selfp->len) {
                return self;
        }
        CE_RANGE_INITIAL(start, end, self->len);
        CeInt i = 0;
        CeInt tmp_len = (end - start) / 2;
        CeUChar tmp_data;
        for(; i <= tmp_len; i++) {
                tmp_data = selfp->data[i + start];
                selfp->data[i + start] = selfp->data[end - i];
                selfp->data[end - i] = tmp_data;
        }
        return self;
}
CeString* ce_string_set_data (CeString * self, const CeUChar * data) [inline]
Setting the data in CeString Object.
Parameters:
self The CeString Object
data A string that you want to put in CeString Object
Returns:
The CeString Object
Definition at line 138 of file cestring.c.
References ce_string_set_data_inrange().
Referenced by ce_string_append_data_inrange(), ce_string_concat_data_inrange(), and ce_string_new_with_data().
{
        return ce_string_set_data_inrange(self, data, 1, -1);
}
CeString* ce_string_set_data_inrange (CeString * self, const CeUChar * data, CeInt start, CeInt end)
Setting the data in range in CeString Object.
Parameters:
self The CeString Object
data A String Object
start The first char is 1, the second is 2, blah blah blah.
end The last char is -1 or the length of String Object
Returns:
The CeString Object
Definition at line 153 of file cestring.c.
References CE_RANGE_INITIAL, and CE_STRING_INITIAL.
Referenced by ce_string_copy_inrange(), ce_string_new_with_data_inrange(), and ce_string_set_data().
{
        CE_STRING_INITIAL();
        CeInt length = strlen(data);
        CE_RANGE_INITIAL(start, end, length);
        length = end - start + 1;
        /* Free the CeString Object first */
        if(0 != selfp->len) {
                free(self->data);
        }
        selfp->len = length;
        selfp->data = (CeUChar *) malloc( sizeof(CeUChar) * (length + 1) );
        /* Now let's copy new string to our CeString */
        memcpy(selfp->data, data + start, length);
        selfp->data[length] = '\0';   /* end of line */
        return self;
}
void ce_string_swap (CeString * selfA, CeString * selfB) [inline]
Swap two CeString Object.
Parameters:
selfA A CeString Object
selfB A CeString Object
Definition at line 521 of file cestring.c.
{
        selfp = (CeStringP *) selfA;
        selfA = selfB;
        selfB = (CeString  *) selfp;
}
CeString* ce_string_tolower (CeString * self) [inline]
Make all the cahracters in CeString object to lowercase.
Parameters:
self The CeString Object
Returns:
The CeString Object
Definition at line 334 of file cestring.c.
References ce_string_tolower_inrange().
{
        return ce_string_tolower_inrange(self, 1, -1);
}
CeString* ce_string_tolower_inrange (CeString * self, CeInt start, CeInt end)
Make the cahracters in CeString object in range to lowercase.
Parameters:
self The CeString Object
start The first char is 1, the second is 2, blah blah blah.
end The last char is -1 or the length of String Object
Returns:
The CeString Object
Definition at line 348 of file cestring.c.
References CE_RANGE_INITIAL, and CE_STRING_INITIAL.
Referenced by ce_string_tolower().
{
        CE_STRING_INITIAL();
        CE_RANGE_INITIAL(start, end, self->len);
        CeInt i = start;
        for (; i <= end; i++) {
                selfp->data[i] = tolower(selfp->data[i]);
        }
        return self;
}
CeString* ce_string_toupper (CeString * self) [inline]
Make all the cahracters in CeString object to uppercase.
Parameters:
self The CeString Object
Returns:
The CeString Object
Definition at line 297 of file cestring.c.
References ce_string_toupper_inrange().
{
        return ce_string_toupper_inrange(self, 1, -1);
}
CeString* ce_string_toupper_inrange (CeString * self, CeInt start, CeInt end)
Make the cahracters in CeString object in range to uppercase.
Parameters:
self The CeString Object
start The first char is 1, the second is 2, blah blah blah.
end The last char is -1 or the length of String Object
Returns:
The CeString Object
Definition at line 311 of file cestring.c.
References CE_RANGE_INITIAL, and CE_STRING_INITIAL.
Referenced by ce_string_toupper().
{
        CE_STRING_INITIAL();
        CE_RANGE_INITIAL(start, end, self->len);
        CeInt i = start;
        for (; i <= end; i++) {
                selfp->data[i] = toupper(selfp->data[i]);
        }
        return self;
}